module EventsHelper
  Quarter_arr = [['1', 1], ['2', 2], ['3', 3], ['4', 4]]
  Event_type = [['SP',1],['LCDEXC',2]]
  Event_month = [['January', 1], ['February', 2], ['March', 3], ['April', 4],['May', 5],['June', 6],['July', 7],['August', 8],['September', 9],['October', 10],['November', 11],['December', 12]]
  Usstates =[
                ['Alabama', 'Alabama'],
                ['Alaska', 'Alaska'],
                ['Arizona', 'Arizona'],
                ['Arkansas', 'Arkansas'],
                ['California', 'California'],
                ['Colorado', 'Colorado'],
                ['Connecticut', 'Connecticut'],
                ['Delaware', 'Delaware'],
                ['District of Columbia', 'District of Columbia'],
                ['Florida', 'Florida'],
                ['Georgia', 'Georgia'],
                ['Hawaii', 'Hawaii'],
                ['Idaho', 'Idaho'],
                ['Illinois', 'Illinois'],
                ['Indiana', 'Indiana'],
                ['Iowa', 'Iowa'],
                ['Kansas', 'Kansas'],
                ['Kentucky', 'Kentucky'],
                ['Louisiana', 'Louisiana'],
                ['Maine', 'Maine'],
                ['Maryland', 'Maryland'],
                ['Massachusetts', 'Massachusetts'],
                ['Michigan', 'Michigan'],
                ['Minnesota', 'Minnesota'],
                ['Mississippi', 'Mississippi'],
                ['Missouri', 'Missouri'],
                ['Montana', 'Montana'],
                ['Nebraska', 'Nebraska'],
                ['Nevada', 'Nevada'],
                ['New Hampshire', 'New Hampshire'],
                ['New Jersey', 'New Jersey'],
                ['New Mexico', 'New Mexico'],
                ['New York', 'New York'],
                ['North Carolina', 'North Carolina'],
                ['North Dakota', 'North Dakota'],
                ['Ohio', 'OH'],
                ['Oklahoma', 'Oklahoma'],
                ['Oregon', 'Oregon'],
                ['Pennsylvania', 'Pennsylvania'],
                ['Puerto Rico', 'Puerto Rico'],
                ['Rhode Island', 'Rhode Island'],
                ['South Carolina', 'South Carolina'],
                ['South Dakota', 'South Dakota'],
                ['Tennessee', 'Tennessee'],
                ['Texas', 'Texas'],
                ['Utah', 'Utah'],
                ['Vermont', 'Vermont'],
                ['Virginia', 'Virginia'],
                ['Washington', 'Washington'],
                ['West Virginia', 'WV'],
                ['Wisconsin', 'Wisconsin'],
                ['Wyoming', 'Wyoming']      ]
end
